-- AlterTable
ALTER TABLE "VirtualAirlineRole" ALTER COLUMN "PayPercent" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "PayWeekly" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "PayPerFlightHour" SET DATA TYPE DOUBLE PRECISION;
