-- AlterTable
ALTER TABLE "public"."Aircraft" ADD COLUMN     "CreatedAt" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "LastRefresh" TIMESTAMP(6),
ADD COLUMN     "UpdatedAt" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;
